  name: Activity-Box
  on:
    schedule:
      - cron: "0 0 * * *"
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - run: npm install
        - run: node index.js
          env:
            GITHUB_EVENT_NAME: schedule
            GH_PAT: ${{ secrets.GH_TOKEN }}
            GH_USERNAME: vouxx
            GIST_ID: a1842a1ebb50bcdbba78b28a38a9cb2d
